export type Theme = 'tech-blue' | 'vitality-orange' | 'dark-green';

export type Page = 'dashboard' | 'inventory' | 'finance' | 'analytics' | 'tracking' | 'calendar' | 'marketing' | 'customers' | 'settings' | 'logistics' | 'product_ai';

export interface ShipmentEvent {
  date: string;
  time: string;
  location: string;
  description: string;
  status: 'Normal' | 'Exception' | 'Delivered' | 'InTransit';
}

export interface Shipment {
  id: string;
  trackingNo: string;
  carrier: string;
  status: 'Pending' | 'InTransit' | 'Delivered' | 'Exception';
  origin: string;
  destination: string;
  productName: string;
  estimatedArrival?: string;
  estimatedDelivery?: string;
  lastUpdateAt: string;
  lastUpdate?: string;
  events: ShipmentEvent[];
  sku?: string;
  shipDate?: string;
  notes?: string;
}

export interface Product { 
  id: string; 
  name: string; 
  sku: string; 
  stock: number; 
  costPrice: number;
  price: number;
  dimensions?: { l: number; w: number; h: number };
  unitWeight?: number;
  logistics?: {
    carrier?: string;
    trackingNo?: string;
    unitFreightCost?: number;
    consumablesFee?: number;
    method?: 'Air' | 'Sea';
    targetWarehouse?: string;
    billingWeight?: number;
    unitBillingWeight?: number;
    totalFreightCost?: number;
    customsFee?: number;
    portFee?: number;
  };
  economics?: {
    platformFeePercent?: number;
    creatorFeePercent?: number;
    fixedCost?: number;
    lastLegShipping?: number;
    adCost?: number;
    refundRatePercent?: number;
  };
  lifecycle?: string;
  leadTime?: number;
  safetyStockDays?: number;
  dailyBurnRate?: number;
  itemsPerBox?: number;
  lingXingId?: string;
  notes?: string;
  image?: string;
  deletedAt?: string;
  boxCount?: number;
  supplier?: string;
  supplierContact?: string;
}

export interface ReplenishmentItem extends Product {
  dailyBurnRate: number;
  daysRemaining: number;
  profit: number;
  margin: number;
  totalInvestment: number;
  liveTrackingStatus: string;
  safetyStock?: number;
  reorderPoint?: number;
  freightCost?: number;
  goodsCost?: number;
  revenue30d?: number;
  growth?: number;
  totalPotentialProfit?: number;
  totalWeight?: number;
  boxes?: number;
}

export interface Order {
  id: string;
  customerName: string;
  total: number;
  status: 'pending' | 'processing' | 'shipped' | 'delivered';
  date: string;
  itemsCount: number;
  lineItems?: Array<{
    sku: string;
    productId: string;
    quantity: number;
    price: number;
  }>;
  deletedAt?: string;
}

export interface Customer {
  id: string;
  name: string;
  company?: string;
  email: string;
  phone?: string;
  level: 'Standard' | 'VIP' | 'Wholesale';
  source: 'Online' | 'Offline' | 'Referral';
  totalSpend: number;
  ordersCount: number;
  status: 'Active' | 'Inactive';
  lastOrderDate: string;
  notes?: string;
  avatarColor?: string;
}

export interface CloudAutomationSettings {
  enableSentinel: boolean;
  enableStockAlert: boolean;
}

export type TransactionType = 'income' | 'expense';

export type TransactionCategory = 'Revenue' | 'COGS' | 'Logistics' | 'Marketing' | 'Software' | 'Office' | 'Payroll' | 'Other';

export type PaymentMethod = 'Bank' | 'PayPal' | 'AliPay' | 'Payoneer' | 'CreditCard';

export interface Transaction {
  id: string;
  type: TransactionType;
  category: TransactionCategory;
  amount: number;
  currency: 'CNY' | 'USD';
  date: string;
  description: string;
  status: 'completed' | 'pending';
  paymentMethod: PaymentMethod;
}

export type EventType = 'logistics' | 'marketing' | 'finance' | 'product' | 'stockout';

export interface CalendarEvent {
  id: string;
  title: string;
  date: string;
  type: EventType;
  description?: string;
  autoGenerated?: boolean;
  sku?: string;
}

export interface Influencer {
  id: string;
  name: string;
  handle: string;
  platform: 'TikTok' | 'YouTube' | 'Instagram';
  followers: number;
  country: string;
  status: 'Prospecting' | 'Negotiating' | 'Pending Sample' | 'Sample Sent' | 'Video Live' | 'Completed';
  tags: string[];
  sampleCost: number;
  generatedSales: number;
  email?: string;
  whatsapp?: string;
  shippingAddress?: string;
  notes?: string;
  videoUrl?: string;
  sampleCarrier?: string;
  sampleProductSku?: string;
  sampleDate?: string;
  sampleTrackingNo?: string;
}

export interface Toast {
  id: string;
  message: string;
  type: 'success' | 'error' | 'warning' | 'info';
}

export interface Integration {
  id: string;
  platform: string;
  name: string;
  region: string;
  status: 'connected' | 'syncing' | 'error';
  lastSync: string;
}

export interface Supplier {
  id: string;
  name: string;
  contactName: string;
  email: string;
  phone: string;
  address: string;
  category: string;
  rating: number;
  paymentTerms: string;
  status: 'Active' | 'Inactive';
  leadTime: number;
}

export interface InboundShipmentItem {
  productId: string;
  sku: string;
  name: string;
  quantity: number;
  boxes: number;
  unitPrice: number;
  rowTotalWeight: number;
  freightRate: number;
}

export interface InboundShipment {
  id: string;
  name: string;
  method: 'Air' | 'Sea';
  trackingNumber: string;
  carrier: string;
  sourceWarehouseId: string;
  destinationWarehouseId: string;
  status: 'Draft' | 'Shipped' | 'Receiving' | 'Closed';
  items: InboundShipmentItem[];
  totalWeight: number;
  totalVolume: number;
  createdDate: string;
  shippedDate?: string;
}

export interface Task {
  id: string;
  title: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'todo' | 'in_progress' | 'review' | 'done';
  assignee: string;
  dueDate: string;
  category: 'procurement' | 'logistics' | 'marketing' | 'finance';
  dependsOn?: string[];
}

export interface GlobalState {
  activePage: Page;
  theme: Theme;
  shipments: Shipment[];
  products: Product[];
  isMobileMenuOpen: boolean;
  isInitialized: boolean;
  toasts: Toast[];
  transactions: Transaction[];
  exchangeRate: number;
  orders: Order[];
  influencers: Influencer[];
  customers: Customer[];
  cloudSettings: CloudAutomationSettings;
  connectionStatus: 'connected' | 'disconnected';
  pbUrl?: string;
  saveStatus?: 'clean' | 'dirty';
  tasks?: Task[];
  suppliers?: Supplier[];
  inboundShipments?: InboundShipment[];
}