
export type Page = 'dashboard' | 'inventory' | 'customers' | 'intelligence' | 'settings' | 'finance' | 'tracking' | 'calendar' | 'marketing' | 'analytics' | 'replenishment' | 'suppliers' | 'calculator' | 'profile' | 'tasks' | 'ai-command' | 'logistics-hub' | 'automation' | 'virtual-warehouse';

export interface User {
  id: string;
  name: string;
  email: string;
  role: 'admin' | 'user';
}

export interface Task {
  id: string;
  title: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'todo' | 'in_progress' | 'review' | 'done';
  assignee: string;
  dueDate: string;
  relatedSku?: string;
  category: 'logistics' | 'marketing' | 'procurement' | 'finance';
  dependsOn?: string[]; 
  autoGenerated?: boolean;
}

export interface ProposedAction {
    id: string;
    type: 'inventory_update' | 'task_creation' | 'finance_entry' | 'status_change';
    description: string;
    payload: any;
    status: 'pending' | 'committed' | 'dismissed';
    confidence: number;
}

export type ProductStatus = 'active' | 'draft' | 'archived' | 'out_of_stock' | 'low_stock';
export type ProductLifecycle = 'New' | 'Growing' | 'Stable' | 'Clearance';

export interface Product {
  id: string;
  name: string;
  sku: string;
  category: string;
  stock: number;
  inventoryBreakdown?: { warehouseId: string; quantity: number; reserved: number; inbound: number }[];
  price: number;
  status: ProductStatus;
  lastUpdated: string;
  dailyBurnRate?: number;
  lifecycle?: ProductLifecycle;
  supplier?: string;
  supplierId?: string;
  supplierContact?: string;
  costPrice?: number;
  leadTime?: number;
  safetyStockDays?: number;
  dimensions?: { l: number; w: number; h: number };
  itemsPerBox?: number;
  boxCount?: number;
  unitWeight?: number;
  warehouseAgeDays?: number; 
  binLocation?: string; // 新增：物理货位, 如 "A-01-04"
  logistics?: { 
    method: 'Air' | 'Sea'; 
    carrier: string; 
    trackingNo: string; 
    unitFreightCost: number; 
    totalFreightCost?: number;
    billingWeight?: number;
    unitBillingWeight?: number;
    consumablesFee?: number;
    customsFee?: number;
    portFee?: number;
    targetWarehouse: string 
  };
  economics?: { 
    platformFeePercent: number; 
    creatorFeePercent: number; 
    fixedCost: number; 
    lastLegShipping: number; 
    adCost: number; 
    refundRatePercent?: number;
    storageFeeMonthly?: number; 
  };
  deletedAt?: string;
  image?: string;
  images?: string[];
  lingXingId?: string;
  notes?: string;
}

export interface InboundShipmentItem {
  productId: string;
  sku: string;
  name: string;
  quantity: number;
  boxes: number;
  unitPrice: number;
  rowTotalWeight: number;
  freightRate: number;
}

export interface ReplenishmentItem extends Product {
  dailyBurnRate: number;
  daysRemaining: number;
  safetyStock: number;
  reorderPoint: number;
  totalInvestment: number;
  freightCost: number;
  goodsCost: number;
  revenue30d: number;
  growth: number;
  profit: number;
  totalPotentialProfit: number;
  margin: number;
  totalWeight: number;
  boxes: number;
  // Added liveTrackingStatus to fix property access errors in Inventory.tsx
  liveTrackingStatus?: string | null;
}

export interface AutomationRule {
    id: string;
    name: string;
    trigger: 'logistics_exception' | 'low_stock_warning' | 'high_refund_rate' | 'new_vip_order';
    action: 'create_task' | 'generate_ai_copy' | 'notify_admin';
    status: 'active' | 'paused';
    lastTriggered?: string;
}

export interface AutomationLog {
    id: string;
    timestamp: string;
    ruleName: string;
    details: string;
    status: 'success' | 'failed';
}

export interface Toast {
  id: string;
  message: string;
  type: 'success' | 'error' | 'warning' | 'info';
}

export type TransactionType = 'income' | 'expense';
export type PaymentMethod = 'Bank' | 'PayPal' | 'CreditCard' | 'AliPay' | 'WeChat' | 'Payoneer' | 'PingPong' | 'Stripe' | 'Other';
export type TransactionCategory = 'Revenue' | 'COGS' | 'Logistics' | 'Marketing' | 'Software' | 'Office' | 'Payroll' | 'Other';

export interface Transaction {
  id: string;
  date: string;
  type: TransactionType;
  category: TransactionCategory;
  amount: number;
  currency: 'USD' | 'CNY' | 'EUR';
  description: string;
  status: 'pending' | 'completed' | 'failed';
  paymentMethod: PaymentMethod;
  tags?: string[];
  relatedOrderId?: string;
  relatedPOId?: string;
}

export interface ShipmentEvent {
  date: string;
  time: string;
  location: string;
  description: string;
  status: 'Normal' | 'Exception' | 'Delivered' | 'InTransit';
}

export interface Shipment {
  id: string;
  trackingNo: string;
  carrier: string;
  status: '待处理' | '运输中' | '已送达' | '异常';
  origin?: string;
  destination?: string;
  estimatedDelivery?: string;
  productName?: string;
  lastUpdate?: string;
  events: ShipmentEvent[];
  shipDate?: string;
  notes?: string;
}

export interface Order {
  id: string;
  customerName: string;
  date: string;
  total: number;
  status: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  itemsCount: number;
  lineItems?: any[];
  paymentStatus?: string;
  deletedAt?: string;
}

export interface InboundShipment {
  id: string;
  name: string;
  method: 'Air' | 'Sea';
  sourceWarehouseId: string;
  destinationWarehouseId: string;
  status: 'Draft' | 'Working' | 'Shipped' | 'Receiving' | 'Closed';
  items: InboundShipmentItem[];
  totalWeight: number;
  totalVolume: number;
  carrier?: string;
  trackingNumber?: string;
  createdDate: string;
  shippedDate?: string;
  eta?: string;
}

export interface Customer {
    id: string;
    name: string;
    company?: string;
    email: string;
    phone?: string;
    level: 'Standard' | 'VIP' | 'Partner' | 'Blocked';
    source: string;
    totalSpend: number;
    ordersCount: number;
    status: 'Active' | 'Inactive';
    lastOrderDate: string;
    avatarColor?: string;
    notes?: string;
}

export interface AuditLog {
    id: string;
    timestamp: string;
    user: string;
    action: string;
    details: string;
}

export interface Supplier {
    id: string;
    name: string;
    contactName: string;
    email: string;
    phone: string;
    address: string;
    category: string;
    rating: number;
    paymentTerms: string;
    status: 'Active' | 'Inactive';
    leadTime: number;
}

export interface SalesData {
  name: string;
  value: number;
}

export interface Warehouse {
  id: string;
  name: string;
  type: string;
  region: string;
}

export interface AdCampaign {
  id: string;
  name: string;
  platform: string;
  status: string;
  budget: number;
  spend: number;
  sales: number;
  acos: number;
  roas: number;
  clicks: number;
  impressions: number;
  ctr: number;
  cpc: number;
}

export interface Influencer {
  id: string;
  name: string;
  handle: string;
  platform: 'TikTok' | 'YouTube' | 'Instagram';
  followers: number;
  country: string;
  status: 'To Contact' | 'Sample Sent' | 'Video Live' | 'Completed';
  sampleProductSku?: string;
  sampleDate?: string;
  sampleCost?: number;
  generatedSales?: number;
  roi?: number;
  tags: string[];
  videoUrl?: string;
}

export interface AiInsight {
    id: string;
    text: string;
    timestamp: string;
}

export type EventType = 'logistics' | 'marketing' | 'finance' | 'product' | 'stockout';

export interface CalendarEvent {
  id: string;
  title: string;
  date: string;
  type: EventType;
  description?: string;
  autoGenerated?: boolean;
  sku?: string;
}

export interface Integration {
  id: string;
  platform: string;
  name: string;
  region: string;
  status: 'connected' | 'syncing' | 'error';
  lastSync: string;
}
