
import React, { useState, useEffect } from 'react';
import { ChevronLeft, ChevronRight, Plus, Calendar as CalendarIcon, Clock, Truck, Megaphone, DollarSign, Package, X, Check, AlertTriangle, Box, Sparkles, Loader2, BrainCircuit } from 'lucide-react';
import { CalendarEvent, EventType } from '../types';
import { useTanxing } from '../context/TanxingContext';
import { GoogleGenAI } from "@google/genai";

const Calendar: React.FC = () => {
  const { state } = useTanxing();
  const [currentDate, setCurrentDate] = useState(new Date());
  const [events, setEvents] = useState<CalendarEvent[]>([]);
  const [selectedDate, setSelectedDate] = useState<Date | null>(null);
  const [showAddModal, setShowAddModal] = useState(false);
  const [newEvent, setNewEvent] = useState<Partial<CalendarEvent>>({
      type: 'logistics',
      title: '',
      description: ''
  });

  // AI State
  const [isAiThinking, setIsAiThinking] = useState(false);

  // Calculate Auto Events from Inventory Data (Rule-based)
  const generateInventoryEvents = (): CalendarEvent[] => {
      const generated: CalendarEvent[] = [];
      const today = new Date();

      state.products.forEach(product => {
          if (!product.dailyBurnRate || product.dailyBurnRate <= 0) return;

          // 1. Calculate Stockout Date
          const daysRemaining = Math.floor(product.stock / product.dailyBurnRate);
          // Limit to next 120 days to avoid clutter
          if (daysRemaining > 120) return;

          const stockoutDate = new Date(today);
          stockoutDate.setDate(today.getDate() + daysRemaining);
          const stockoutDateStr = stockoutDate.toISOString().split('T')[0];

          generated.push({
              id: `AUTO-STOCKOUT-${product.id}`,
              title: `⚠️ ${product.sku} 预计断货`,
              date: stockoutDateStr,
              type: 'stockout',
              description: `当前库存: ${product.stock}, 日均消耗: ${product.dailyBurnRate}。建议立即补货。`,
              autoGenerated: true,
              sku: product.sku
          });

          // 2. Calculate Reorder Date
          const leadTime = product.leadTime || 15;
          const safetyStockDays = product.safetyStockDays || 7;
          const reorderThresholdDays = leadTime + safetyStockDays;
          
          const daysUntilReorder = daysRemaining - reorderThresholdDays;
          
          if (daysUntilReorder <= 0) {
             // Already late, handled by immediate dashboard alerts usually
          } else {
             const reorderDate = new Date(today);
             reorderDate.setDate(today.getDate() + daysUntilReorder);
             const reorderDateStr = reorderDate.toISOString().split('T')[0];

             generated.push({
                 id: `AUTO-REORDER-${product.id}`,
                 title: `📝 ${product.sku} 建议下单`,
                 date: reorderDateStr,
                 type: 'product',
                 description: `交期: ${leadTime}天, 安全库存: ${safetyStockDays}天。`,
                 autoGenerated: true,
                 sku: product.sku
             });
          }
      });

      return generated;
  };

  useEffect(() => {
      const today = new Date();
      const y = today.getFullYear();
      const m = today.getMonth();
      
      const manualEvents: CalendarEvent[] = [
          { id: '1', title: 'CP-Q1M 补货到仓', date: `${y}-${String(m+1).padStart(2, '0')}-05`, type: 'logistics', description: '预计500件入库 US-WEST' },
          { id: '2', title: '新品发布会直播', date: `${y}-${String(m+1).padStart(2, '0')}-12`, type: 'marketing', description: 'TikTok Shop 专场' },
          { id: '3', title: '供应商付款日', date: `${y}-${String(m+1).padStart(2, '0')}-15`, type: 'finance', description: '支付深圳工厂Q3尾款' },
          { id: '4', title: 'K7500 键盘首发', date: `${y}-${String(m+1).padStart(2, '0')}-20`, type: 'product', description: '全渠道上线' },
          { id: '5', title: '黑色星期五备货', date: `${y}-${String(m+1).padStart(2, '0')}-28`, type: 'logistics', description: '截止入仓时间' },
      ];

      const autoEvents = generateInventoryEvents();
      
      setEvents(prev => {
          // Keep AI events if they exist from previous state, overwrite others
          const existingAiEvents = prev.filter(e => e.id.startsWith('AI-GEN-'));
          return [...manualEvents, ...autoEvents, ...existingAiEvents];
      });
  }, [state.products]); // Re-run when products change

  // --- AI Generation Logic ---
  const handleAiSchedule = async () => {
      setIsAiThinking(true);
      try {
          if (!process.env.API_KEY) throw new Error("API Key missing");
          const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

          // 1. Prepare Context Data (Summarized to save tokens)
          const todayStr = new Date().toISOString().split('T')[0];
          const lowStockSkus = state.products
              .filter(p => p.stock < 20)
              .map(p => `${p.sku}(Stock:${p.stock})`)
              .join(', ');
          const activeShipments = state.shipments
              .filter(s => s.status !== 'Delivered')
              .map(s => `${s.trackingNo}(Status:${s.status}, ETA:${s.estimatedDelivery})`)
              .join(', ');
          const recentSpend = state.transactions
              .filter(t => t.type === 'expense')
              .slice(0, 5)
              .map(t => `${t.category}: $${t.amount}`)
              .join(', ');

          // 2. Prompt Construction
          const prompt = `
            Act as an E-commerce Operations Director. 
            Current Date: ${todayStr}.
            
            Context Data:
            - Low Stock Items: ${lowStockSkus || 'None'}
            - Active Shipments: ${activeShipments || 'None'}
            - Recent Expenses: ${recentSpend}
            - Upcoming Global Events: Black Friday, Cyber Monday, Christmas (if applicable based on current date).

            Task: Generate 3-5 critical operational calendar events for the next 30 days to optimize business flow.
            
            Return ONLY a valid JSON array of objects. No markdown formatting.
            Schema:
            [{
                "title": "Short Title (Chinese)",
                "date": "YYYY-MM-DD",
                "type": "logistics" | "marketing" | "finance" | "product",
                "description": "Actionable advice (Chinese)"
            }]
          `;

          const response = await ai.models.generateContent({
              model: 'gemini-2.5-flash',
              contents: prompt,
              config: { responseMimeType: "application/json" }
          });

          // 3. Parse and Merge
          const text = response.text || '[]';
          // Clean potential markdown just in case model ignores config
          const jsonStr = text.replace(/```json/g, '').replace(/```/g, '').trim();
          const aiEvents = JSON.parse(jsonStr);

          const formattedEvents: CalendarEvent[] = aiEvents.map((e: any, idx: number) => ({
              id: `AI-GEN-${Date.now()}-${idx}`,
              title: `✨ ${e.title}`,
              date: e.date,
              type: e.type,
              description: e.description,
              autoGenerated: true
          }));

          setEvents(prev => [
              ...prev.filter(e => !e.id.startsWith('AI-GEN-')), // Remove old AI events
              ...formattedEvents
          ]);

      } catch (error) {
          console.error("AI Scheduling Failed", error);
          alert("AI 暂时无法生成排期，请稍后再试");
      } finally {
          setIsAiThinking(false);
      }
  };

  const getDaysInMonth = (year: number, month: number) => new Date(year, month + 1, 0).getDate();
  const getFirstDayOfMonth = (year: number, month: number) => new Date(year, month, 1).getDay();

  const handlePrevMonth = () => {
      setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1));
  };

  const handleNextMonth = () => {
      setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1));
  };

  const handleDateClick = (day: number) => {
      const date = new Date(currentDate.getFullYear(), currentDate.getMonth(), day);
      setSelectedDate(date);
      setNewEvent({ ...newEvent, date: date.toISOString().split('T')[0] });
      setShowAddModal(true);
  };

  const handleAddEvent = () => {
      if (!newEvent.title || !newEvent.date) return;
      
      const event: CalendarEvent = {
          id: `EVT-${Date.now()}`,
          title: newEvent.title!,
          date: newEvent.date!,
          type: newEvent.type as EventType,
          description: newEvent.description
      };
      
      setEvents([...events, event]);
      setShowAddModal(false);
      setNewEvent({ type: 'logistics', title: '', description: '' });
  };

  const handleDeleteEvent = (id: string, e: React.MouseEvent) => {
      e.stopPropagation();
      if(confirm('确定删除此事件吗？')) {
          setEvents(events.filter(ev => ev.id !== id));
      }
  };

  const renderCalendarGrid = () => {
      const year = currentDate.getFullYear();
      const month = currentDate.getMonth();
      const daysInMonth = getDaysInMonth(year, month);
      const firstDay = getFirstDayOfMonth(year, month);
      const days = [];

      for (let i = 0; i < firstDay; i++) {
          days.push(<div key={`pad-${i}`} className="h-32 bg-slate-950/30 border border-slate-800/50"></div>);
      }

      for (let day = 1; day <= daysInMonth; day++) {
          const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
          const dayEvents = events.filter(e => e.date === dateStr);
          const isToday = new Date().toDateString() === new Date(year, month, day).toDateString();

          days.push(
              <div 
                  key={day} 
                  onClick={() => handleDateClick(day)}
                  className={`h-32 border border-slate-800 p-2 relative group hover:bg-slate-800/30 transition-colors cursor-pointer ${isToday ? 'bg-indigo-900/10' : 'bg-slate-900'}`}
              >
                  <div className={`text-xs font-medium mb-1 ${isToday ? 'text-indigo-400 bg-indigo-500/10 px-2 py-0.5 rounded w-fit' : 'text-slate-500'}`}>
                      {isToday ? '今天' : day}
                  </div>
                  
                  <div className="space-y-1 overflow-y-auto max-h-[90px] scrollbar-none">
                      {dayEvents.map(ev => (
                          <div 
                              key={ev.id}
                              className={`text-[10px] px-1.5 py-1 rounded border truncate flex items-center gap-1 group/event cursor-help transition-all ${
                                  ev.id.startsWith('AI-GEN-') ? 'border-indigo-500/50 bg-indigo-500/10 text-indigo-300 shadow-[0_0_10px_rgba(99,102,241,0.1)]' :
                                  ev.type === 'logistics' ? 'bg-blue-500/10 border-blue-500/20 text-blue-300' :
                                  ev.type === 'marketing' ? 'bg-purple-500/10 border-purple-500/20 text-purple-300' :
                                  ev.type === 'finance' ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-300' :
                                  ev.type === 'product' ? 'bg-amber-500/10 border-amber-500/20 text-amber-300' :
                                  ev.type === 'stockout' ? 'bg-red-500/10 border-red-500/20 text-red-300' :
                                  'bg-slate-700/50 border-slate-600 text-slate-300'
                              }`}
                              title={ev.description}
                          >
                              <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${
                                  ev.id.startsWith('AI-GEN-') ? 'bg-indigo-400 animate-pulse' :
                                  ev.type === 'logistics' ? 'bg-blue-500' :
                                  ev.type === 'marketing' ? 'bg-purple-500' :
                                  ev.type === 'finance' ? 'bg-emerald-500' :
                                  ev.type === 'product' ? 'bg-amber-500' :
                                  ev.type === 'stockout' ? 'bg-red-500' :
                                  'bg-slate-500'
                              }`}></span>
                              <span className="truncate">{ev.title}</span>
                              {ev.autoGenerated && !ev.id.startsWith('AI-GEN-') && <span className="text-[8px] bg-slate-800 px-1 rounded ml-1 text-slate-500">Auto</span>}
                              
                              {!ev.autoGenerated && (
                                <button 
                                    onClick={(e) => handleDeleteEvent(ev.id, e)}
                                    className="ml-auto opacity-0 group-hover/event:opacity-100 hover:text-red-400"
                                >
                                    <X className="w-3 h-3" />
                                </button>
                              )}
                          </div>
                      ))}
                  </div>

                  <button className="absolute top-2 right-2 text-slate-600 hover:text-white opacity-0 group-hover:opacity-100 transition-opacity">
                      <Plus className="w-4 h-4" />
                  </button>
              </div>
          );
      }

      return days;
  };

  const MONTH_NAMES = ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"];

  return (
    <div className="h-[calc(100vh-6rem)] flex flex-col space-y-4">
      
      {/* Calendar Header */}
      <div className="flex flex-col md:flex-row justify-between items-center gap-4 bg-slate-900 p-4 rounded-xl border border-slate-800 shadow-sm">
          <div className="flex items-center gap-4">
              <div className="flex items-center bg-slate-950 rounded-lg p-1 border border-slate-800">
                  <button onClick={handlePrevMonth} className="p-1 hover:bg-slate-800 rounded text-slate-400 hover:text-white transition-colors">
                      <ChevronLeft className="w-5 h-5" />
                  </button>
                  <div className="px-4 font-mono font-bold text-white text-lg w-40 text-center">
                      {MONTH_NAMES[currentDate.getMonth()]} {currentDate.getFullYear()}
                  </div>
                  <button onClick={handleNextMonth} className="p-1 hover:bg-slate-800 rounded text-slate-400 hover:text-white transition-colors">
                      <ChevronRight className="w-5 h-5" />
                  </button>
              </div>
              <button 
                  onClick={() => setCurrentDate(new Date())}
                  className="text-xs px-3 py-1.5 border border-slate-700 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
              >
                  回到今天
              </button>
              
              {/* AI Button */}
              <button 
                  onClick={handleAiSchedule}
                  disabled={isAiThinking}
                  className="relative group px-4 py-1.5 bg-gradient-to-r from-indigo-900/50 to-purple-900/50 border border-indigo-500/30 rounded-lg text-indigo-300 text-xs font-bold hover:text-white hover:border-indigo-400 transition-all flex items-center gap-2 overflow-hidden disabled:opacity-50 disabled:cursor-not-allowed"
              >
                  <div className="absolute inset-0 bg-gradient-to-r from-indigo-500/10 to-purple-500/10 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                  {isAiThinking ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <BrainCircuit className="w-3.5 h-3.5" />}
                  {isAiThinking ? 'AI 运算中...' : 'AI 智能排期'}
              </button>
          </div>

          <div className="flex gap-4 overflow-x-auto pb-1 md:pb-0 scrollbar-none w-full md:w-auto">
              <div className="flex items-center gap-1.5 text-xs text-blue-400 whitespace-nowrap">
                  <span className="w-2 h-2 rounded-full bg-blue-500"></span> 物流
              </div>
              <div className="flex items-center gap-1.5 text-xs text-purple-400 whitespace-nowrap">
                  <span className="w-2 h-2 rounded-full bg-purple-500"></span> 营销
              </div>
              <div className="flex items-center gap-1.5 text-xs text-emerald-400 whitespace-nowrap">
                  <span className="w-2 h-2 rounded-full bg-emerald-500"></span> 财务
              </div>
              <div className="flex items-center gap-1.5 text-xs text-amber-400 whitespace-nowrap">
                  <span className="w-2 h-2 rounded-full bg-amber-500"></span> 备货
              </div>
              <div className="flex items-center gap-1.5 text-xs text-indigo-400 whitespace-nowrap">
                  <span className="w-2 h-2 rounded-full bg-indigo-500 animate-pulse"></span> AI 建议
              </div>
          </div>
      </div>

      {/* Calendar Body */}
      <div className="flex-1 bg-slate-900 rounded-xl border border-slate-800 shadow-sm overflow-hidden flex flex-col">
          {/* Weekday Header */}
          <div className="grid grid-cols-7 border-b border-slate-800 bg-slate-950/50">
              {['周日', '周一', '周二', '周三', '周四', '周五', '周六'].map(day => (
                  <div key={day} className="py-3 text-center text-xs font-bold text-slate-500 tracking-wider">
                      {day}
                  </div>
              ))}
          </div>
          
          {/* Days Grid */}
          <div className="grid grid-cols-7 flex-1 overflow-y-auto">
              {renderCalendarGrid()}
          </div>
      </div>

      {/* Add Event Modal */}
      {showAddModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 backdrop-blur-sm bg-black/60" onClick={() => setShowAddModal(false)}>
              <div className="bg-slate-900 w-full max-w-md rounded-2xl border border-slate-800 shadow-2xl p-6 animate-in zoom-in-95 duration-200" onClick={e => e.stopPropagation()}>
                  <div className="flex justify-between items-center mb-6">
                      <h3 className="text-lg font-bold text-white flex items-center gap-2">
                          <CalendarIcon className="w-5 h-5 text-indigo-500" />
                          新增日程
                      </h3>
                      <button onClick={() => setShowAddModal(false)}><X className="w-5 h-5 text-slate-500 hover:text-white" /></button>
                  </div>

                  <div className="space-y-4">
                      <div className="space-y-1">
                          <label className="text-xs text-slate-400">事件类型</label>
                          <div className="grid grid-cols-2 gap-2">
                              <button 
                                  onClick={() => setNewEvent({ ...newEvent, type: 'logistics' })}
                                  className={`flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium border transition-all ${newEvent.type === 'logistics' ? 'bg-blue-500/20 border-blue-500 text-blue-300' : 'bg-slate-950 border-slate-700 text-slate-400 hover:bg-slate-800'}`}
                              >
                                  <Truck className="w-3.5 h-3.5" /> 物流节点
                              </button>
                              <button 
                                  onClick={() => setNewEvent({ ...newEvent, type: 'marketing' })}
                                  className={`flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium border transition-all ${newEvent.type === 'marketing' ? 'bg-purple-500/20 border-purple-500 text-purple-300' : 'bg-slate-950 border-slate-700 text-slate-400 hover:bg-slate-800'}`}
                              >
                                  <Megaphone className="w-3.5 h-3.5" /> 营销活动
                              </button>
                              <button 
                                  onClick={() => setNewEvent({ ...newEvent, type: 'finance' })}
                                  className={`flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium border transition-all ${newEvent.type === 'finance' ? 'bg-emerald-500/20 border-emerald-500 text-emerald-300' : 'bg-slate-950 border-slate-700 text-slate-400 hover:bg-slate-800'}`}
                              >
                                  <DollarSign className="w-3.5 h-3.5" /> 财务/付款
                              </button>
                              <button 
                                  onClick={() => setNewEvent({ ...newEvent, type: 'product' })}
                                  className={`flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium border transition-all ${newEvent.type === 'product' ? 'bg-amber-500/20 border-amber-500 text-amber-300' : 'bg-slate-950 border-slate-700 text-slate-400 hover:bg-slate-800'}`}
                              >
                                  <Package className="w-3.5 h-3.5" /> 产品/备货
                              </button>
                          </div>
                      </div>

                      <div className="space-y-1">
                          <label className="text-xs text-slate-400">标题</label>
                          <input 
                              type="text" 
                              value={newEvent.title}
                              onChange={(e) => setNewEvent({ ...newEvent, title: e.target.value })}
                              className="w-full px-3 py-2 bg-slate-950 border border-slate-700 rounded-lg text-sm text-white focus:outline-none focus:border-indigo-500"
                              placeholder="e.g. 500件新品入库"
                          />
                      </div>

                      <div className="space-y-1">
                          <label className="text-xs text-slate-400">日期</label>
                          <input 
                              type="date" 
                              value={newEvent.date}
                              onChange={(e) => setNewEvent({ ...newEvent, date: e.target.value })}
                              className="w-full px-3 py-2 bg-slate-950 border border-slate-700 rounded-lg text-sm text-white focus:outline-none focus:border-indigo-500"
                          />
                      </div>

                      <div className="space-y-1">
                          <label className="text-xs text-slate-400">备注详情</label>
                          <textarea 
                              value={newEvent.description}
                              onChange={(e) => setNewEvent({ ...newEvent, description: e.target.value })}
                              className="w-full h-20 px-3 py-2 bg-slate-950 border border-slate-700 rounded-lg text-sm text-white focus:outline-none focus:border-indigo-500 resize-none"
                              placeholder="添加详细说明..."
                          />
                      </div>
                  </div>

                  <div className="mt-6 flex gap-3">
                      <button onClick={() => setShowAddModal(false)} className="flex-1 py-2 bg-slate-800 hover:bg-slate-700 text-white rounded-lg text-sm">取消</button>
                      <button 
                          onClick={handleAddEvent}
                          className="flex-1 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-sm font-bold shadow-lg shadow-indigo-900/40 flex items-center justify-center gap-2"
                      >
                          <Check className="w-4 h-4" /> 确认添加
                      </button>
                  </div>
              </div>
          </div>
      )}
    </div>
  );
};

export default Calendar;
