
import React, { useState, useEffect } from 'react';
import { ChevronLeft, ChevronRight, Plus, Calendar as CalendarIcon, Clock, Truck, Megaphone, DollarSign, Package, X, Check, AlertTriangle, Box, Sparkles, Loader2, BrainCircuit, LayoutGrid, Columns, Settings2 } from 'lucide-react';
import { CalendarEvent, EventType } from '../types';
import { useTanxing } from '../context/TanxingContext';
import { GoogleGenAI } from "@google/genai";

const Calendar: React.FC = () => {
  const { state } = useTanxing();
  const [currentDate, setCurrentDate] = useState(new Date());
  const [events, setEvents] = useState<CalendarEvent[]>([]);
  const [selectedDate, setSelectedDate] = useState<Date | null>(null);
  const [showAddModal, setShowAddModal] = useState(false);
  
  // New: Track deleted auto-generated events to prevent them from reappearing
  const [deletedEventIds, setDeletedEventIds] = useState<Set<string>>(new Set());

  // New View States
  const [viewMode, setViewMode] = useState<'month' | 'week'>('month');
  const [weekStartDay, setWeekStartDay] = useState<0 | 1>(1); // 0 = Sun, 1 = Mon
  
  const [newEvent, setNewEvent] = useState<Partial<CalendarEvent>>({
      type: 'logistics',
      title: '',
      description: ''
  });

  // AI State
  const [isAiThinking, setIsAiThinking] = useState(false);

  // --- Helper Functions ---

  const getEventStyle = (type: EventType, isAi: boolean) => {
      const baseStyle = "text-[10px] px-2 py-1.5 rounded-md border truncate flex items-center gap-1.5 group/event cursor-pointer transition-all hover:scale-[1.02] shadow-sm";
      
      if (isAi) return `${baseStyle} border-indigo-500/50 bg-indigo-500/10 text-indigo-300 shadow-[0_0_10px_rgba(99,102,241,0.1)]`;
      
      switch (type) {
          case 'logistics': return `${baseStyle} bg-blue-500/10 border-blue-500/30 text-blue-300 hover:bg-blue-500/20`;
          case 'marketing': return `${baseStyle} bg-purple-500/10 border-purple-500/30 text-purple-300 hover:bg-purple-500/20`;
          case 'finance': return `${baseStyle} bg-emerald-500/10 border-emerald-500/30 text-emerald-300 hover:bg-emerald-500/20`;
          case 'product': return `${baseStyle} bg-amber-500/10 border-amber-500/30 text-amber-300 hover:bg-amber-500/20`;
          case 'stockout': return `${baseStyle} bg-red-500/10 border-red-500/30 text-red-300 hover:bg-red-500/20`;
          default: return `${baseStyle} bg-slate-700/50 border-slate-600 text-slate-300`;
      }
  };

  const getEventIconColor = (type: EventType, isAi: boolean) => {
      if (isAi) return 'bg-indigo-400 animate-pulse';
      switch (type) {
          case 'logistics': return 'bg-blue-500';
          case 'marketing': return 'bg-purple-500';
          case 'finance': return 'bg-emerald-500';
          case 'product': return 'bg-amber-500';
          case 'stockout': return 'bg-red-500';
          default: return 'bg-slate-500';
      }
  };

  // 1. Calculate Inventory Alerts (Already Real)
  const generateInventoryEvents = (): CalendarEvent[] => {
      const generated: CalendarEvent[] = [];
      const today = new Date();

      state.products.forEach(product => {
          if (!product.dailyBurnRate || product.dailyBurnRate <= 0) return;

          // Stockout Date
          const daysRemaining = Math.floor(product.stock / product.dailyBurnRate);
          if (daysRemaining > 90) return;

          const stockoutDate = new Date(today);
          stockoutDate.setDate(today.getDate() + daysRemaining);
          const stockoutDateStr = stockoutDate.toISOString().split('T')[0];

          generated.push({
              id: `AUTO-STOCKOUT-${product.id}`,
              title: `⚠️ ${product.sku} 预计断货`,
              date: stockoutDateStr,
              type: 'stockout',
              description: `当前库存: ${product.stock}, 日均消耗: ${product.dailyBurnRate}。建议立即补货。`,
              autoGenerated: true,
              sku: product.sku
          });

          // Reorder Date
          const leadTime = product.leadTime || 15;
          const safetyStockDays = product.safetyStockDays || 7;
          const reorderThresholdDays = leadTime + safetyStockDays;
          const daysUntilReorder = daysRemaining - reorderThresholdDays;
          
          if (daysUntilReorder > 0 && daysUntilReorder < 90) {
             const reorderDate = new Date(today);
             reorderDate.setDate(today.getDate() + daysUntilReorder);
             const reorderDateStr = reorderDate.toISOString().split('T')[0];

             generated.push({
                 id: `AUTO-REORDER-${product.id}`,
                 title: `📝 ${product.sku} 建议下单`,
                 date: reorderDateStr,
                 type: 'product',
                 description: `交期: ${leadTime}天, 安全库存: ${safetyStockDays}天。`,
                 autoGenerated: true,
                 sku: product.sku
             });
          }
      });
      return generated;
  };

  // 2. Generate Logistics Events from Tracking Data (NEW Real Data Source)
  const generateLogisticsEvents = (): CalendarEvent[] => {
      const events: CalendarEvent[] = [];
      state.shipments.forEach(shipment => {
          if (shipment.estimatedDelivery && shipment.status !== '已送达') {
              // Convert "2023-10-28" format directly or parse if needed
              // Assuming ISO format YYYY-MM-DD from Tracking page
              events.push({
                  id: `LOG-ETA-${shipment.id}`,
                  title: `🚢 ${shipment.carrier} 到港 (${shipment.trackingNo.slice(-4)})`,
                  date: shipment.estimatedDelivery, // Ensure this matches format
                  type: 'logistics',
                  description: `${shipment.productName} 预计到达. Status: ${shipment.status}`,
                  autoGenerated: true
              });
          }
      });
      return events;
  };

  // 3. Generate Finance Events (NEW Real Data Source)
  const generateFinanceEvents = (): CalendarEvent[] => {
      const events: CalendarEvent[] = [];
      state.transactions.forEach(tx => {
          if (tx.status === 'pending') {
              events.push({
                  id: `FIN-PENDING-${tx.id}`,
                  title: `💰 待处理: ${tx.category}`,
                  date: tx.date,
                  type: 'finance',
                  description: `${tx.description} - ${tx.currency} ${tx.amount}`,
                  autoGenerated: true
              });
          }
      });
      return events;
  };

  useEffect(() => {
      // Combine all Real Data sources
      const inventoryEvents = generateInventoryEvents();
      const logisticsEvents = generateLogisticsEvents();
      const financeEvents = generateFinanceEvents();
      
      const allAutoEvents = [...inventoryEvents, ...logisticsEvents, ...financeEvents];
      // Filter out events that were explicitly deleted
      const activeAutoEvents = allAutoEvents.filter(e => !deletedEventIds.has(e.id));

      setEvents(prev => {
          // Keep manually added AI events and manual events
          const existingManualEvents = prev.filter(e => !e.autoGenerated && !e.id.startsWith('AUTO-') && !e.id.startsWith('LOG-') && !e.id.startsWith('FIN-'));
          const existingAiEvents = prev.filter(e => e.id.startsWith('AI-GEN-'));
          
          return [...existingManualEvents, ...existingAiEvents, ...activeAutoEvents];
      });
  }, [state.products, state.shipments, state.transactions, deletedEventIds]); // Depend on deletedEventIds

  // --- AI Generation Logic ---
  const handleAiSchedule = async () => {
      setIsAiThinking(true);
      try {
          if (!process.env.API_KEY) throw new Error("API Key missing");
          const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

          const todayStr = new Date().toISOString().split('T')[0];
          const lowStockSkus = state.products
              .filter(p => p.stock < 20)
              .map(p => `${p.sku}(Stock:${p.stock})`)
              .join(', ');
          
          const prompt = `
            Act as an E-commerce Operations Director. 
            Current Date: ${todayStr}.
            Context Data: Low Stock Items: ${lowStockSkus || 'None'}.
            Task: Generate 3 critical operational calendar events for the next 30 days.
            Return ONLY a valid JSON array of objects. Schema:
            [{ "title": "String", "date": "YYYY-MM-DD", "type": "logistics"|"marketing"|"finance"|"product", "description": "String" }]
          `;

          const response = await ai.models.generateContent({
              model: 'gemini-2.5-flash',
              contents: prompt,
              config: { responseMimeType: "application/json" }
          });

          const jsonStr = (response.text || '[]').replace(/```json/g, '').replace(/```/g, '').trim();
          const aiEvents = JSON.parse(jsonStr);

          const formattedEvents: CalendarEvent[] = aiEvents.map((e: any, idx: number) => ({
              id: `AI-GEN-${Date.now()}-${idx}`,
              title: `✨ ${e.title}`,
              date: e.date,
              type: e.type,
              description: e.description,
              autoGenerated: true
          }));

          setEvents(prev => [...prev.filter(e => !e.id.startsWith('AI-GEN-')), ...formattedEvents]);

      } catch (error) {
          console.error("AI Scheduling Failed", error);
      } finally {
          setIsAiThinking(false);
      }
  };

  // --- Date Navigation ---
  const handlePrev = () => {
      const newDate = new Date(currentDate);
      if (viewMode === 'month') {
          newDate.setMonth(newDate.getMonth() - 1);
      } else {
          newDate.setDate(newDate.getDate() - 7);
      }
      setCurrentDate(newDate);
  };

  const handleNext = () => {
      const newDate = new Date(currentDate);
      if (viewMode === 'month') {
          newDate.setMonth(newDate.getMonth() + 1);
      } else {
          newDate.setDate(newDate.getDate() + 7);
      }
      setCurrentDate(newDate);
  };

  const handleToday = () => setCurrentDate(new Date());

  const handleDateClick = (date: Date) => {
      setSelectedDate(date);
      setNewEvent({ ...newEvent, date: date.toISOString().split('T')[0] });
      setShowAddModal(true);
  };

  const handleAddEvent = () => {
      if (!newEvent.title || !newEvent.date) return;
      const event: CalendarEvent = {
          id: `EVT-${Date.now()}`,
          title: newEvent.title!,
          date: newEvent.date!,
          type: newEvent.type as EventType,
          description: newEvent.description
      };
      setEvents([...events, event]);
      setShowAddModal(false);
      setNewEvent({ type: 'logistics', title: '', description: '' });
  };

  const handleDeleteEvent = (id: string, e: React.MouseEvent) => {
      e.stopPropagation();
      if(confirm('确定删除此事件吗？')) {
          setEvents(prev => prev.filter(ev => ev.id !== id));
          // If it's an auto-generated ID, add it to the ignore list
          if (id.startsWith('AUTO-') || id.startsWith('LOG-') || id.startsWith('FIN-')) {
              setDeletedEventIds(prev => new Set(prev).add(id));
          }
      }
  };

  // --- Grid Renderers ---
  const getWeekDaysHeader = () => {
      const days = ['周日', '周一', '周二', '周三', '周四', '周五', '周六'];
      if (weekStartDay === 1) {
          return [...days.slice(1), days[0]];
      }
      return days;
  };

  const renderMonthView = () => {
      const year = currentDate.getFullYear();
      const month = currentDate.getMonth();
      const daysInMonth = new Date(year, month + 1, 0).getDate();
      const firstDayOfMonth = new Date(year, month, 1).getDay();
      
      const padding = (firstDayOfMonth - weekStartDay + 7) % 7;
      
      const days = [];

      for (let i = 0; i < padding; i++) {
          days.push(<div key={`pad-${i}`} className="min-h-[120px] bg-black/60 border border-white/5"></div>);
      }

      for (let day = 1; day <= daysInMonth; day++) {
          const date = new Date(year, month, day);
          const dateStr = date.toISOString().split('T')[0];
          const dayEvents = events.filter(e => e.date === dateStr);
          const isToday = new Date().toDateString() === date.toDateString();

          days.push(
              <div 
                  key={day} 
                  onClick={() => handleDateClick(date)}
                  className={`min-h-[120px] border border-white/5 p-2 relative group hover:bg-white/5 transition-colors cursor-pointer flex flex-col gap-1 ${isToday ? 'bg-indigo-900/10' : 'bg-black/20'}`}
              >
                  <div className="flex justify-between items-start">
                      <div className={`text-xs font-medium mb-1 ${isToday ? 'text-indigo-400 bg-indigo-500/10 px-2 py-0.5 rounded w-fit' : 'text-slate-500'}`}>
                          {day}
                      </div>
                      <button className="text-slate-600 hover:text-white opacity-0 group-hover:opacity-100 transition-opacity">
                          <Plus className="w-3 h-3" />
                      </button>
                  </div>
                  
                  <div className="flex-1 space-y-1 overflow-y-auto scrollbar-none">
                      {dayEvents.map(ev => {
                          const isAi = ev.id.startsWith('AI-GEN-');
                          return (
                              <div key={ev.id} className={getEventStyle(ev.type, isAi)} title={ev.description}>
                                  <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${getEventIconColor(ev.type, isAi)}`}></span>
                                  <span className="truncate">{ev.title}</span>
                                  {/* Enabled deletion for all events */}
                                  <button onClick={(e) => handleDeleteEvent(ev.id, e)} className="ml-auto opacity-0 group-hover/event:opacity-100 hover:text-red-400">
                                      <X className="w-3 h-3" />
                                  </button>
                              </div>
                          );
                      })}
                  </div>
              </div>
          );
      }
      return days;
  };

  const renderWeekView = () => {
      const currentDay = currentDate.getDay(); 
      const diff = (currentDay - weekStartDay + 7) % 7;
      
      const startOfWeek = new Date(currentDate);
      startOfWeek.setDate(currentDate.getDate() - diff);

      const days = [];
      for (let i = 0; i < 7; i++) {
          const date = new Date(startOfWeek);
          date.setDate(startOfWeek.getDate() + i);
          const dateStr = date.toISOString().split('T')[0];
          const dayEvents = events.filter(e => e.date === dateStr);
          const isToday = new Date().toDateString() === date.toDateString();

          days.push(
              <div 
                  key={i} 
                  onClick={() => handleDateClick(date)}
                  className={`border-r last:border-r-0 border-white/10 p-3 relative group hover:bg-white/5 transition-colors cursor-pointer flex flex-col h-full ${isToday ? 'bg-indigo-900/10' : 'bg-black/20'}`}
              >
                  <div className={`text-center py-2 mb-2 border-b border-white/10 ${isToday ? 'bg-indigo-500/10 text-indigo-400 rounded-lg' : ''}`}>
                      <div className="text-xs text-slate-500 uppercase">{getWeekDaysHeader()[i]}</div>
                      <div className={`text-xl font-bold ${isToday ? 'text-indigo-400' : 'text-slate-300'}`}>{date.getDate()}</div>
                  </div>

                  <div className="flex-1 space-y-2 overflow-y-auto scrollbar-none py-2">
                      {dayEvents.map(ev => {
                          const isAi = ev.id.startsWith('AI-GEN-');
                          return (
                              <div key={ev.id} className={`${getEventStyle(ev.type, isAi)} py-3 flex-col items-start gap-1`} title={ev.description}>
                                  <div className="flex items-center gap-2 w-full">
                                      <span className={`w-2 h-2 rounded-full shrink-0 ${getEventIconColor(ev.type, isAi)}`}></span>
                                      <span className="truncate font-bold">{ev.title}</span>
                                  </div>
                                  <div className="text-[9px] text-slate-400 pl-4 line-clamp-2 leading-tight">
                                      {ev.description || '无详细描述'}
                                  </div>
                                  {/* Enabled deletion for all events */}
                                  <button onClick={(e) => handleDeleteEvent(ev.id, e)} className="absolute top-2 right-2 opacity-0 group-hover/event:opacity-100 hover:text-red-400">
                                      <X className="w-3 h-3" />
                                  </button>
                              </div>
                          );
                      })}
                      
                      <button className="w-full py-2 border-2 border-dashed border-white/10 rounded text-slate-600 hover:border-slate-500 hover:text-slate-400 text-xs flex items-center justify-center opacity-0 group-hover:opacity-100 transition-all">
                          <Plus className="w-3 h-3 mr-1" /> 添加
                      </button>
                  </div>
              </div>
          );
      }
      return days;
  };

  const getHeaderTitle = () => {
      const y = currentDate.getFullYear();
      const m = currentDate.getMonth();
      const monthName = ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"][m];
      
      if (viewMode === 'month') {
          return `${monthName} ${y}`;
      } else {
          const day = currentDate.getDay();
          const diff = (day - weekStartDay + 7) % 7;
          const startOfWeek = new Date(currentDate);
          startOfWeek.setDate(currentDate.getDate() - diff);
          
          const endOfWeek = new Date(startOfWeek);
          endOfWeek.setDate(startOfWeek.getDate() + 6);
          
          return `${startOfWeek.getMonth()+1}月${startOfWeek.getDate()}日 - ${endOfWeek.getMonth()+1}月${endOfWeek.getDate()}日`;
      }
  };

  return (
    <div className="h-[calc(100vh-6rem)] flex flex-col space-y-4">
      {/* Calendar Header */}
      <div className="flex flex-col md:flex-row justify-between items-center gap-4 bg-black/20 p-4 rounded-xl border border-white/10 shadow-sm backdrop-blur-sm">
          <div className="flex items-center gap-4">
              <div className="flex items-center bg-black/40 rounded-lg p-1 border border-white/10">
                  <button onClick={handlePrev} className="p-1.5 hover:bg-white/10 rounded text-slate-400 hover:text-white transition-colors">
                      <ChevronLeft className="w-5 h-5" />
                  </button>
                  <div className="px-4 font-mono font-bold text-white text-lg w-48 text-center truncate">
                      {getHeaderTitle()}
                  </div>
                  <button onClick={handleNext} className="p-1.5 hover:bg-white/10 rounded text-slate-400 hover:text-white transition-colors">
                      <ChevronRight className="w-5 h-5" />
                  </button>
              </div>
              <button onClick={handleToday} className="text-xs px-3 py-1.5 border border-white/10 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 transition-colors">
                  今天
              </button>
              <button 
                  onClick={handleAiSchedule}
                  disabled={isAiThinking}
                  className="hidden md:flex relative group px-4 py-1.5 bg-gradient-to-r from-indigo-900/50 to-purple-900/50 border border-indigo-500/30 rounded-lg text-indigo-300 text-xs font-bold hover:text-white hover:border-indigo-400 transition-all items-center gap-2 overflow-hidden disabled:opacity-50"
              >
                  <div className="absolute inset-0 bg-gradient-to-r from-indigo-500/10 to-purple-500/10 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                  {isAiThinking ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <BrainCircuit className="w-3.5 h-3.5" />}
                  {isAiThinking ? 'AI 运算中...' : 'AI 智能排期'}
              </button>
          </div>

          <div className="flex items-center gap-4">
              <div className="flex bg-black/40 p-1 rounded-lg border border-white/10">
                  <button onClick={() => setViewMode('month')} className={`px-3 py-1 rounded-md text-xs font-bold transition-colors flex items-center gap-2 ${viewMode === 'month' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'}`}>
                      <LayoutGrid className="w-3 h-3" /> 月视图
                  </button>
                  <button onClick={() => setViewMode('week')} className={`px-3 py-1 rounded-md text-xs font-bold transition-colors flex items-center gap-2 ${viewMode === 'week' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'}`}>
                      <Columns className="w-3 h-3" /> 周视图
                  </button>
              </div>
              <button 
                  onClick={() => setWeekStartDay(weekStartDay === 1 ? 0 : 1)}
                  className="flex items-center gap-2 px-3 py-1.5 border border-white/10 rounded-lg text-slate-400 text-xs hover:text-white hover:bg-white/10 transition-colors"
                  title="切换每周起始日"
              >
                  <Settings2 className="w-3 h-3" />
                  {weekStartDay === 1 ? '周一作为起始' : '周日作为起始'}
              </button>
          </div>
      </div>

      {/* Calendar Grid */}
      <div className="flex-1 bg-black/20 rounded-xl border border-white/10 shadow-sm overflow-hidden flex flex-col backdrop-blur-sm">
          <div className={`grid ${viewMode === 'month' ? 'grid-cols-7' : 'grid-cols-7'} border-b border-white/10 bg-black/40`}>
              {getWeekDaysHeader().map(day => (
                  <div key={day} className="py-3 text-center text-xs font-bold text-slate-500 tracking-wider">
                      {day}
                  </div>
              ))}
          </div>
          <div className={`grid ${viewMode === 'month' ? 'grid-cols-7 auto-rows-fr' : 'grid-cols-7 h-full'} flex-1 overflow-y-auto bg-transparent`}>
              {viewMode === 'month' ? renderMonthView() : renderWeekView()}
          </div>
      </div>

      {/* Legend Footer */}
      <div className="flex flex-wrap gap-4 px-4 py-2 bg-black/40 rounded-xl border border-white/10 justify-center text-xs text-slate-400">
          <div className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-blue-500"></span> 物流</div>
          <div className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-purple-500"></span> 营销</div>
          <div className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-emerald-500"></span> 财务</div>
          <div className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-amber-500"></span> 备货</div>
          <div className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-red-500"></span> 缺货</div>
          <div className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-indigo-500 animate-pulse"></span> AI 建议</div>
      </div>

      {/* Add Event Modal */}
      {showAddModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 backdrop-blur-sm bg-black/60" onClick={() => setShowAddModal(false)}>
              <div className="bg-[#0a0a0a] w-full max-w-md rounded-2xl border border-white/10 shadow-2xl p-6 animate-in zoom-in-95 duration-200" onClick={e => e.stopPropagation()}>
                  <div className="flex justify-between items-center mb-6">
                      <h3 className="text-lg font-bold text-white flex items-center gap-2">
                          <CalendarIcon className="w-5 h-5 text-indigo-500" />
                          新增日程
                      </h3>
                      <button onClick={() => setShowAddModal(false)}><X className="w-5 h-5 text-slate-500 hover:text-white" /></button>
                  </div>

                  <div className="space-y-4">
                      <div className="space-y-1">
                          <label className="text-xs text-slate-400">事件类型</label>
                          <div className="grid grid-cols-2 gap-2">
                              <button onClick={() => setNewEvent({ ...newEvent, type: 'logistics' })} className={`flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium border transition-all ${newEvent.type === 'logistics' ? 'bg-blue-500/20 border-blue-500 text-blue-300' : 'bg-black/60 border-white/10 text-slate-400 hover:bg-white/5'}`}><Truck className="w-3.5 h-3.5" /> 物流节点</button>
                              <button onClick={() => setNewEvent({ ...newEvent, type: 'marketing' })} className={`flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium border transition-all ${newEvent.type === 'marketing' ? 'bg-purple-500/20 border-purple-500 text-purple-300' : 'bg-black/60 border-white/10 text-slate-400 hover:bg-white/5'}`}><Megaphone className="w-3.5 h-3.5" /> 营销活动</button>
                              <button onClick={() => setNewEvent({ ...newEvent, type: 'finance' })} className={`flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium border transition-all ${newEvent.type === 'finance' ? 'bg-emerald-500/20 border-emerald-500 text-emerald-300' : 'bg-black/60 border-white/10 text-slate-400 hover:bg-white/5'}`}><DollarSign className="w-3.5 h-3.5" /> 财务/付款</button>
                              <button onClick={() => setNewEvent({ ...newEvent, type: 'product' })} className={`flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium border transition-all ${newEvent.type === 'product' ? 'bg-amber-500/20 border-amber-500 text-amber-300' : 'bg-black/60 border-white/10 text-slate-400 hover:bg-white/5'}`}><Package className="w-3.5 h-3.5" /> 产品/备货</button>
                          </div>
                      </div>

                      <div className="space-y-1">
                          <label className="text-xs text-slate-400">标题</label>
                          <input type="text" value={newEvent.title} onChange={(e) => setNewEvent({ ...newEvent, title: e.target.value })} className="w-full px-3 py-2 bg-black/60 border border-white/10 rounded-lg text-sm text-white focus:outline-none focus:border-indigo-500" placeholder="e.g. 500件新品入库" />
                      </div>

                      <div className="space-y-1">
                          <label className="text-xs text-slate-400">日期</label>
                          <input type="date" value={newEvent.date} onChange={(e) => setNewEvent({ ...newEvent, date: e.target.value })} className="w-full px-3 py-2 bg-black/60 border border-white/10 rounded-lg text-sm text-white focus:outline-none focus:border-indigo-500" />
                      </div>

                      <div className="space-y-1">
                          <label className="text-xs text-slate-400">备注详情</label>
                          <textarea value={newEvent.description} onChange={(e) => setNewEvent({ ...newEvent, description: e.target.value })} className="w-full h-20 px-3 py-2 bg-black/60 border border-white/10 rounded-lg text-sm text-white focus:outline-none focus:border-indigo-500 resize-none" placeholder="添加详细说明..." />
                      </div>
                  </div>

                  <div className="mt-6 flex gap-3">
                      <button onClick={() => setShowAddModal(false)} className="flex-1 py-2 bg-white/5 hover:bg-white/10 text-white rounded-lg text-sm">取消</button>
                      <button onClick={handleAddEvent} className="flex-1 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-sm font-bold shadow-lg shadow-indigo-900/40 flex items-center justify-center gap-2"><Check className="w-4 h-4" /> 确认添加</button>
                  </div>
              </div>
          </div>
      )}
    </div>
  );
};

export default Calendar;
